### ISSUE TITLE
Need to fix TMS upload

### ISSUE THREAD

**Issue by jywarren** [publiclab/mapknitter-exporter-sinatra#141]
```
         6: from /home/gitpod/.rvm/gems/ruby-2.6.6/gems/mapknitter-exporter-1.0.9/lib/mapknitterExporter.rb:390:in `run_export'
         5: from /workspace/mapknitter-exporter-sinatra/lib/export.rb:81:in `save'
         4: from /workspace/mapknitter-exporter-sinatra/lib/export.rb:63:in `check_status'
         3: from /workspace/mapknitter-exporter-sinatra/lib/export.rb:63:in `each'
         2: from /workspace/mapknitter-exporter-sinatra/lib/export.rb:67:in `block in check_status'
         1: from /workspace/mapknitter-exporter-sinatra/lib/export.rb:67:in `open'
/workspace/mapknitter-exporter-sinatra/lib/export.rb:67:in `initialize': No such file or directory @ rb_sysopen - openlayers.html (Errno::ENOENT)
```

**Comment by jywarren** [comment]
Should be able to do `File.exists?(path)` but... really shouldn't need to!!!

**Comment by jywarren** [comment]
Solved in https://github.com/publiclab/mapknitter-exporter-sinatra/commit/f9d1130601e0bbf099d5bbec5bf92b7f7f133dde !!

https://mapknitter-exports-warps.storage.googleapis.com/1635967115/tms/openlayers.html
