### ISSUE TITLE
Sinatra times out

### ISSUE THREAD

**Issue by jywarren** [publiclab/mapknitter-exporter-sinatra#20]
Looking here, it seems like we are timing out even in the forked process. I wonder if the 300 second limit is applied to forks; i'll try increasing it. 

```

2019-04-30T15:23:29.840292Z> generating geotiffs of each warpable in GDAL
2019-04-30T15:23:29.840305Zwarping 1 of 3
2019-04-30T15:24:48.238748Zconvert -contrast-stretch 0 public/warps/306187-working/w306187-DJI_1207.JPG -crop 3968x3968+0+0! -flatten -distort Perspective '0,0 0,648 3968,0 123,0 3968,2976 589,83 0,2976 465,732' -flatten -crop 732x732+0+0! +repage public/warps/13015/w306187.png
2019-04-30T15:28:17.639592Z== Sinatra has ended his set (crowd applauds)
2019-04-30T15:28:17.938489Z/usr/lib/ruby/2.5.0/net/http.rb:937:in `initialize': execution expired (Net::OpenTimeout)
2019-04-30T15:28:17.938597Z	from /usr/lib/ruby/2.5.0/net/http.rb:937:in `open'
2019-04-30T15:28:17.938615Z	from /usr/lib/ruby/2.5.0/net/http.rb:937:in `block in connect'
2019-04-30T15:28:17.938626Z	from /usr/lib/ruby/2.5.0/timeout.rb:103:in `timeout'
2019-04-30T15:28:17.938636Z	from /usr/lib/ruby/2.5.0/net/http.rb:935:in `connect'
2019-04-30T15:28:17.938648Z	from /usr/lib/ruby/2.5.0/net/http.rb:920:in `do_start'
2019-04-30T15:28:17.938657Z	from /usr/lib/ruby/2.5.0/net/http.rb:909:in `start'
2019-04-30T15:28:17.938677Z	from /usr/lib/ruby/2.5.0/net/http.rb:609:in `start'
```

**Comment by jywarren** [comment]
Tried setting it to 900s, or 15 minutes.

**Comment by jywarren** [comment]
If we run into trouble doing a big export, is there a way to run processes on a bigger container, or for longer than 900 seconds?

**Comment by jywarren** [comment]
Great, moving to https://github.com/publiclab/mapknitter-exporter-sinatra/issues/23 after our new http://e.mapknitter.org cluster
